### ISSUE TITLE
Roll back last merge from me.

### ISSUE THREAD

**Issue by ff6347** [thomasgeissl/ofxNDI#2]
The lib I added is v3 for linux. It does not work well with the existing header files. v1 Seems to be deprecated. I suggest creating a v3 and adding the SDK and headers for v3 there. I will link my version ASAP here.

**Comment by ff6347** [comment]
FYI https://github.com/fabianmoronzirfas/ofxNDI3

**Comment by thomasgeissl** [comment]
it should be reverted. i suggest to update this addon to v3 and maybe tag the current version as v1 and add a proper changelog. i will have a look next week.
